FROM node:22-alpine
WORKDIR /app
COPY server.js /app/server.js
COPY www/ /www/
ENV PORT=3000
ENV SYNC_TOKEN=""
ENV DATA_FILE=/data/data.json
ENV WWW_DIR=/www
ENV TDOC_CLIENT_ID=""
ENV TDOC_ACCESS_TOKEN=""
ENV TDOC_OPEN_ID=""
ENV TDOC_FILE_ID=""
ENV TDOC_FILE_TYPE="doc"
ENV TDOC_SHEET_ID=""
EXPOSE 3000
CMD ["node", "server.js"]
